// source: v1alpha/runtime.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var v1alpha_graph_pb = require('../v1alpha/graph_pb.js');
goog.object.extend(proto, v1alpha_graph_pb);
var v1alpha_signature_pb = require('../v1alpha/signature_pb.js');
goog.object.extend(proto, v1alpha_signature_pb);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.AwaitTaskRequest', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.AwaitTaskResponse', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.Callback', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.DeleteTaskRequest', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.DeleteTaskResponse', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.GetTaskRequest', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.GetTaskResponse', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.ListTasksRequest', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.ListTasksResponse', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.RunGraphRequest', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.RunGraphResponse', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.RunGraphResponse.ResultCase', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.RunTaskRequest', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.RunTaskResponse', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.RunTaskResponse.ResultCase', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.Task', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.runtime.Task.StatusCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.Callback = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.Callback, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.Callback.displayName = 'proto.tierkreis.v1alpha.runtime.Callback';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.RunTaskRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.RunTaskRequest.displayName = 'proto.tierkreis.v1alpha.runtime.RunTaskRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.tierkreis.v1alpha.runtime.RunTaskResponse.oneofGroups_);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.RunTaskResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.RunTaskResponse.displayName = 'proto.tierkreis.v1alpha.runtime.RunTaskResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.ListTasksRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.ListTasksRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.ListTasksRequest.displayName = 'proto.tierkreis.v1alpha.runtime.ListTasksRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.ListTasksResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tierkreis.v1alpha.runtime.ListTasksResponse.repeatedFields_, null);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.ListTasksResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.ListTasksResponse.displayName = 'proto.tierkreis.v1alpha.runtime.ListTasksResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.DeleteTaskRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.displayName = 'proto.tierkreis.v1alpha.runtime.DeleteTaskRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.DeleteTaskResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.DeleteTaskResponse.displayName = 'proto.tierkreis.v1alpha.runtime.DeleteTaskResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.GetTaskRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.GetTaskRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.GetTaskRequest.displayName = 'proto.tierkreis.v1alpha.runtime.GetTaskRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.GetTaskResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.GetTaskResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.GetTaskResponse.displayName = 'proto.tierkreis.v1alpha.runtime.GetTaskResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.AwaitTaskRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.displayName = 'proto.tierkreis.v1alpha.runtime.AwaitTaskRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.AwaitTaskResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.displayName = 'proto.tierkreis.v1alpha.runtime.AwaitTaskResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.Task = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.tierkreis.v1alpha.runtime.Task.oneofGroups_);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.Task, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.Task.displayName = 'proto.tierkreis.v1alpha.runtime.Task';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.RunGraphRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.RunGraphRequest.displayName = 'proto.tierkreis.v1alpha.runtime.RunGraphRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.tierkreis.v1alpha.runtime.RunGraphResponse.oneofGroups_);
};
goog.inherits(proto.tierkreis.v1alpha.runtime.RunGraphResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.runtime.RunGraphResponse.displayName = 'proto.tierkreis.v1alpha.runtime.RunGraphResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.Callback.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.Callback.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.Callback} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.Callback.toObject = function(includeInstance, msg) {
  var f, obj = {
    uri: jspb.Message.getFieldWithDefault(msg, 1, ""),
    loc: (f = msg.getLoc()) && v1alpha_graph_pb.Location.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.Callback}
 */
proto.tierkreis.v1alpha.runtime.Callback.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.Callback;
  return proto.tierkreis.v1alpha.runtime.Callback.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.Callback} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.Callback}
 */
proto.tierkreis.v1alpha.runtime.Callback.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    case 2:
      var value = new v1alpha_graph_pb.Location;
      reader.readMessage(value,v1alpha_graph_pb.Location.deserializeBinaryFromReader);
      msg.setLoc(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.Callback.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.Callback.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.Callback} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.Callback.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUri();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLoc();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      v1alpha_graph_pb.Location.serializeBinaryToWriter
    );
  }
};


/**
 * optional string uri = 1;
 * @return {string}
 */
proto.tierkreis.v1alpha.runtime.Callback.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tierkreis.v1alpha.runtime.Callback} returns this
 */
proto.tierkreis.v1alpha.runtime.Callback.prototype.setUri = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional tierkreis.v1alpha.graph.Location loc = 2;
 * @return {?proto.tierkreis.v1alpha.graph.Location}
 */
proto.tierkreis.v1alpha.runtime.Callback.prototype.getLoc = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.Location} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.Location, 2));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.Location|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.Callback} returns this
*/
proto.tierkreis.v1alpha.runtime.Callback.prototype.setLoc = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.Callback} returns this
 */
proto.tierkreis.v1alpha.runtime.Callback.prototype.clearLoc = function() {
  return this.setLoc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.Callback.prototype.hasLoc = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.RunTaskRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.RunTaskRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    graph: (f = msg.getGraph()) && v1alpha_graph_pb.Graph.toObject(includeInstance, f),
    inputs: (f = msg.getInputs()) && v1alpha_graph_pb.StructValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskRequest}
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.RunTaskRequest;
  return proto.tierkreis.v1alpha.runtime.RunTaskRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.RunTaskRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskRequest}
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v1alpha_graph_pb.Graph;
      reader.readMessage(value,v1alpha_graph_pb.Graph.deserializeBinaryFromReader);
      msg.setGraph(value);
      break;
    case 2:
      var value = new v1alpha_graph_pb.StructValue;
      reader.readMessage(value,v1alpha_graph_pb.StructValue.deserializeBinaryFromReader);
      msg.setInputs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.RunTaskRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.RunTaskRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGraph();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      v1alpha_graph_pb.Graph.serializeBinaryToWriter
    );
  }
  f = message.getInputs();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      v1alpha_graph_pb.StructValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional tierkreis.v1alpha.graph.Graph graph = 1;
 * @return {?proto.tierkreis.v1alpha.graph.Graph}
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.prototype.getGraph = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.Graph} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.Graph, 1));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.Graph|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskRequest} returns this
*/
proto.tierkreis.v1alpha.runtime.RunTaskRequest.prototype.setGraph = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskRequest} returns this
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.prototype.clearGraph = function() {
  return this.setGraph(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.prototype.hasGraph = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional tierkreis.v1alpha.graph.StructValue inputs = 2;
 * @return {?proto.tierkreis.v1alpha.graph.StructValue}
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.prototype.getInputs = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.StructValue} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.StructValue, 2));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.StructValue|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskRequest} returns this
*/
proto.tierkreis.v1alpha.runtime.RunTaskRequest.prototype.setInputs = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskRequest} returns this
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.prototype.clearInputs = function() {
  return this.setInputs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunTaskRequest.prototype.hasInputs = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.ResultCase = {
  RESULT_NOT_SET: 0,
  TASK_ID: 1,
  TYPE_ERRORS: 2
};

/**
 * @return {proto.tierkreis.v1alpha.runtime.RunTaskResponse.ResultCase}
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.prototype.getResultCase = function() {
  return /** @type {proto.tierkreis.v1alpha.runtime.RunTaskResponse.ResultCase} */(jspb.Message.computeOneofCase(this, proto.tierkreis.v1alpha.runtime.RunTaskResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.RunTaskResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.RunTaskResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    taskId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    typeErrors: (f = msg.getTypeErrors()) && v1alpha_signature_pb.TypeErrors.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskResponse}
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.RunTaskResponse;
  return proto.tierkreis.v1alpha.runtime.RunTaskResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.RunTaskResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskResponse}
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaskId(value);
      break;
    case 2:
      var value = new v1alpha_signature_pb.TypeErrors;
      reader.readMessage(value,v1alpha_signature_pb.TypeErrors.deserializeBinaryFromReader);
      msg.setTypeErrors(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.RunTaskResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.RunTaskResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTypeErrors();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      v1alpha_signature_pb.TypeErrors.serializeBinaryToWriter
    );
  }
};


/**
 * optional string task_id = 1;
 * @return {string}
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.prototype.getTaskId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskResponse} returns this
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.prototype.setTaskId = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.tierkreis.v1alpha.runtime.RunTaskResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskResponse} returns this
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.prototype.clearTaskId = function() {
  return jspb.Message.setOneofField(this, 1, proto.tierkreis.v1alpha.runtime.RunTaskResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.prototype.hasTaskId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional tierkreis.v1alpha.signature.TypeErrors type_errors = 2;
 * @return {?proto.tierkreis.v1alpha.signature.TypeErrors}
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.prototype.getTypeErrors = function() {
  return /** @type{?proto.tierkreis.v1alpha.signature.TypeErrors} */ (
    jspb.Message.getWrapperField(this, v1alpha_signature_pb.TypeErrors, 2));
};


/**
 * @param {?proto.tierkreis.v1alpha.signature.TypeErrors|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskResponse} returns this
*/
proto.tierkreis.v1alpha.runtime.RunTaskResponse.prototype.setTypeErrors = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.tierkreis.v1alpha.runtime.RunTaskResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.RunTaskResponse} returns this
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.prototype.clearTypeErrors = function() {
  return this.setTypeErrors(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunTaskResponse.prototype.hasTypeErrors = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.ListTasksRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.ListTasksRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.ListTasksRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.ListTasksRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.ListTasksRequest}
 */
proto.tierkreis.v1alpha.runtime.ListTasksRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.ListTasksRequest;
  return proto.tierkreis.v1alpha.runtime.ListTasksRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.ListTasksRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.ListTasksRequest}
 */
proto.tierkreis.v1alpha.runtime.ListTasksRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.ListTasksRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.ListTasksRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.ListTasksRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.ListTasksRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tierkreis.v1alpha.runtime.ListTasksResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.ListTasksResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.ListTasksResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.ListTasksResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.ListTasksResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    tasksList: jspb.Message.toObjectList(msg.getTasksList(),
    proto.tierkreis.v1alpha.runtime.Task.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.ListTasksResponse}
 */
proto.tierkreis.v1alpha.runtime.ListTasksResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.ListTasksResponse;
  return proto.tierkreis.v1alpha.runtime.ListTasksResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.ListTasksResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.ListTasksResponse}
 */
proto.tierkreis.v1alpha.runtime.ListTasksResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tierkreis.v1alpha.runtime.Task;
      reader.readMessage(value,proto.tierkreis.v1alpha.runtime.Task.deserializeBinaryFromReader);
      msg.addTasks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.ListTasksResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.ListTasksResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.ListTasksResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.ListTasksResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTasksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.tierkreis.v1alpha.runtime.Task.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Task tasks = 1;
 * @return {!Array<!proto.tierkreis.v1alpha.runtime.Task>}
 */
proto.tierkreis.v1alpha.runtime.ListTasksResponse.prototype.getTasksList = function() {
  return /** @type{!Array<!proto.tierkreis.v1alpha.runtime.Task>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tierkreis.v1alpha.runtime.Task, 1));
};


/**
 * @param {!Array<!proto.tierkreis.v1alpha.runtime.Task>} value
 * @return {!proto.tierkreis.v1alpha.runtime.ListTasksResponse} returns this
*/
proto.tierkreis.v1alpha.runtime.ListTasksResponse.prototype.setTasksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.tierkreis.v1alpha.runtime.Task=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tierkreis.v1alpha.runtime.Task}
 */
proto.tierkreis.v1alpha.runtime.ListTasksResponse.prototype.addTasks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.tierkreis.v1alpha.runtime.Task, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tierkreis.v1alpha.runtime.ListTasksResponse} returns this
 */
proto.tierkreis.v1alpha.runtime.ListTasksResponse.prototype.clearTasksList = function() {
  return this.setTasksList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.DeleteTaskRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.DeleteTaskRequest}
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.DeleteTaskRequest;
  return proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.DeleteTaskRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.DeleteTaskRequest}
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.DeleteTaskRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tierkreis.v1alpha.runtime.DeleteTaskRequest} returns this
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.DeleteTaskResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.DeleteTaskResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.DeleteTaskResponse}
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.DeleteTaskResponse;
  return proto.tierkreis.v1alpha.runtime.DeleteTaskResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.DeleteTaskResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.DeleteTaskResponse}
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.DeleteTaskResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.DeleteTaskResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.DeleteTaskResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.GetTaskRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.GetTaskRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.GetTaskRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.GetTaskRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.GetTaskRequest}
 */
proto.tierkreis.v1alpha.runtime.GetTaskRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.GetTaskRequest;
  return proto.tierkreis.v1alpha.runtime.GetTaskRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.GetTaskRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.GetTaskRequest}
 */
proto.tierkreis.v1alpha.runtime.GetTaskRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.GetTaskRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.GetTaskRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.GetTaskRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.GetTaskRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.tierkreis.v1alpha.runtime.GetTaskRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tierkreis.v1alpha.runtime.GetTaskRequest} returns this
 */
proto.tierkreis.v1alpha.runtime.GetTaskRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.GetTaskResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.GetTaskResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.GetTaskResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.GetTaskResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    task: (f = msg.getTask()) && proto.tierkreis.v1alpha.runtime.Task.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.GetTaskResponse}
 */
proto.tierkreis.v1alpha.runtime.GetTaskResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.GetTaskResponse;
  return proto.tierkreis.v1alpha.runtime.GetTaskResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.GetTaskResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.GetTaskResponse}
 */
proto.tierkreis.v1alpha.runtime.GetTaskResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tierkreis.v1alpha.runtime.Task;
      reader.readMessage(value,proto.tierkreis.v1alpha.runtime.Task.deserializeBinaryFromReader);
      msg.setTask(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.GetTaskResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.GetTaskResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.GetTaskResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.GetTaskResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTask();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.tierkreis.v1alpha.runtime.Task.serializeBinaryToWriter
    );
  }
};


/**
 * optional Task task = 1;
 * @return {?proto.tierkreis.v1alpha.runtime.Task}
 */
proto.tierkreis.v1alpha.runtime.GetTaskResponse.prototype.getTask = function() {
  return /** @type{?proto.tierkreis.v1alpha.runtime.Task} */ (
    jspb.Message.getWrapperField(this, proto.tierkreis.v1alpha.runtime.Task, 1));
};


/**
 * @param {?proto.tierkreis.v1alpha.runtime.Task|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.GetTaskResponse} returns this
*/
proto.tierkreis.v1alpha.runtime.GetTaskResponse.prototype.setTask = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.GetTaskResponse} returns this
 */
proto.tierkreis.v1alpha.runtime.GetTaskResponse.prototype.clearTask = function() {
  return this.setTask(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.GetTaskResponse.prototype.hasTask = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.AwaitTaskRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timeout: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.AwaitTaskRequest}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.AwaitTaskRequest;
  return proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.AwaitTaskRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.AwaitTaskRequest}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimeout(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.AwaitTaskRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimeout();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tierkreis.v1alpha.runtime.AwaitTaskRequest} returns this
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 timeout = 2;
 * @return {number}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.prototype.getTimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.tierkreis.v1alpha.runtime.AwaitTaskRequest} returns this
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskRequest.prototype.setTimeout = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.AwaitTaskResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    task: (f = msg.getTask()) && proto.tierkreis.v1alpha.runtime.Task.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.AwaitTaskResponse}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.AwaitTaskResponse;
  return proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.AwaitTaskResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.AwaitTaskResponse}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tierkreis.v1alpha.runtime.Task;
      reader.readMessage(value,proto.tierkreis.v1alpha.runtime.Task.deserializeBinaryFromReader);
      msg.setTask(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.AwaitTaskResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTask();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.tierkreis.v1alpha.runtime.Task.serializeBinaryToWriter
    );
  }
};


/**
 * optional Task task = 1;
 * @return {?proto.tierkreis.v1alpha.runtime.Task}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.prototype.getTask = function() {
  return /** @type{?proto.tierkreis.v1alpha.runtime.Task} */ (
    jspb.Message.getWrapperField(this, proto.tierkreis.v1alpha.runtime.Task, 1));
};


/**
 * @param {?proto.tierkreis.v1alpha.runtime.Task|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.AwaitTaskResponse} returns this
*/
proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.prototype.setTask = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.AwaitTaskResponse} returns this
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.prototype.clearTask = function() {
  return this.setTask(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.AwaitTaskResponse.prototype.hasTask = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.tierkreis.v1alpha.runtime.Task.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.tierkreis.v1alpha.runtime.Task.StatusCase = {
  STATUS_NOT_SET: 0,
  SUCCESS: 2,
  ERROR: 3
};

/**
 * @return {proto.tierkreis.v1alpha.runtime.Task.StatusCase}
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.getStatusCase = function() {
  return /** @type {proto.tierkreis.v1alpha.runtime.Task.StatusCase} */(jspb.Message.computeOneofCase(this, proto.tierkreis.v1alpha.runtime.Task.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.Task.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.Task} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.Task.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    success: (f = msg.getSuccess()) && v1alpha_graph_pb.StructValue.toObject(includeInstance, f),
    error: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.Task}
 */
proto.tierkreis.v1alpha.runtime.Task.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.Task;
  return proto.tierkreis.v1alpha.runtime.Task.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.Task} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.Task}
 */
proto.tierkreis.v1alpha.runtime.Task.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new v1alpha_graph_pb.StructValue;
      reader.readMessage(value,v1alpha_graph_pb.StructValue.deserializeBinaryFromReader);
      msg.setSuccess(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.Task.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.Task} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.Task.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSuccess();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      v1alpha_graph_pb.StructValue.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tierkreis.v1alpha.runtime.Task} returns this
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional tierkreis.v1alpha.graph.StructValue success = 2;
 * @return {?proto.tierkreis.v1alpha.graph.StructValue}
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.getSuccess = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.StructValue} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.StructValue, 2));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.StructValue|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.Task} returns this
*/
proto.tierkreis.v1alpha.runtime.Task.prototype.setSuccess = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.tierkreis.v1alpha.runtime.Task.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.Task} returns this
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.clearSuccess = function() {
  return this.setSuccess(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.hasSuccess = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string error = 3;
 * @return {string}
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.tierkreis.v1alpha.runtime.Task} returns this
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.setError = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.tierkreis.v1alpha.runtime.Task.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.Task} returns this
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.clearError = function() {
  return jspb.Message.setOneofField(this, 3, proto.tierkreis.v1alpha.runtime.Task.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.Task.prototype.hasError = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.RunGraphRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    graph: (f = msg.getGraph()) && v1alpha_graph_pb.Graph.toObject(includeInstance, f),
    inputs: (f = msg.getInputs()) && v1alpha_graph_pb.StructValue.toObject(includeInstance, f),
    typeCheck: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    loc: (f = msg.getLoc()) && v1alpha_graph_pb.Location.toObject(includeInstance, f),
    escape: (f = msg.getEscape()) && proto.tierkreis.v1alpha.runtime.Callback.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphRequest}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.RunGraphRequest;
  return proto.tierkreis.v1alpha.runtime.RunGraphRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphRequest}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v1alpha_graph_pb.Graph;
      reader.readMessage(value,v1alpha_graph_pb.Graph.deserializeBinaryFromReader);
      msg.setGraph(value);
      break;
    case 2:
      var value = new v1alpha_graph_pb.StructValue;
      reader.readMessage(value,v1alpha_graph_pb.StructValue.deserializeBinaryFromReader);
      msg.setInputs(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTypeCheck(value);
      break;
    case 4:
      var value = new v1alpha_graph_pb.Location;
      reader.readMessage(value,v1alpha_graph_pb.Location.deserializeBinaryFromReader);
      msg.setLoc(value);
      break;
    case 5:
      var value = new proto.tierkreis.v1alpha.runtime.Callback;
      reader.readMessage(value,proto.tierkreis.v1alpha.runtime.Callback.deserializeBinaryFromReader);
      msg.setEscape(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.RunGraphRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGraph();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      v1alpha_graph_pb.Graph.serializeBinaryToWriter
    );
  }
  f = message.getInputs();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      v1alpha_graph_pb.StructValue.serializeBinaryToWriter
    );
  }
  f = message.getTypeCheck();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getLoc();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      v1alpha_graph_pb.Location.serializeBinaryToWriter
    );
  }
  f = message.getEscape();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.tierkreis.v1alpha.runtime.Callback.serializeBinaryToWriter
    );
  }
};


/**
 * optional tierkreis.v1alpha.graph.Graph graph = 1;
 * @return {?proto.tierkreis.v1alpha.graph.Graph}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.getGraph = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.Graph} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.Graph, 1));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.Graph|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} returns this
*/
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.setGraph = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} returns this
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.clearGraph = function() {
  return this.setGraph(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.hasGraph = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional tierkreis.v1alpha.graph.StructValue inputs = 2;
 * @return {?proto.tierkreis.v1alpha.graph.StructValue}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.getInputs = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.StructValue} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.StructValue, 2));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.StructValue|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} returns this
*/
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.setInputs = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} returns this
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.clearInputs = function() {
  return this.setInputs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.hasInputs = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool type_check = 3;
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.getTypeCheck = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} returns this
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.setTypeCheck = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional tierkreis.v1alpha.graph.Location loc = 4;
 * @return {?proto.tierkreis.v1alpha.graph.Location}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.getLoc = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.Location} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.Location, 4));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.Location|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} returns this
*/
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.setLoc = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} returns this
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.clearLoc = function() {
  return this.setLoc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.hasLoc = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Callback escape = 5;
 * @return {?proto.tierkreis.v1alpha.runtime.Callback}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.getEscape = function() {
  return /** @type{?proto.tierkreis.v1alpha.runtime.Callback} */ (
    jspb.Message.getWrapperField(this, proto.tierkreis.v1alpha.runtime.Callback, 5));
};


/**
 * @param {?proto.tierkreis.v1alpha.runtime.Callback|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} returns this
*/
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.setEscape = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphRequest} returns this
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.clearEscape = function() {
  return this.setEscape(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunGraphRequest.prototype.hasEscape = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.ResultCase = {
  RESULT_NOT_SET: 0,
  SUCCESS: 1,
  ERROR: 2,
  TYPE_ERRORS: 3
};

/**
 * @return {proto.tierkreis.v1alpha.runtime.RunGraphResponse.ResultCase}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.getResultCase = function() {
  return /** @type {proto.tierkreis.v1alpha.runtime.RunGraphResponse.ResultCase} */(jspb.Message.computeOneofCase(this, proto.tierkreis.v1alpha.runtime.RunGraphResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.runtime.RunGraphResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.runtime.RunGraphResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: (f = msg.getSuccess()) && v1alpha_graph_pb.StructValue.toObject(includeInstance, f),
    error: jspb.Message.getFieldWithDefault(msg, 2, ""),
    typeErrors: (f = msg.getTypeErrors()) && v1alpha_signature_pb.TypeErrors.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphResponse}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.runtime.RunGraphResponse;
  return proto.tierkreis.v1alpha.runtime.RunGraphResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.runtime.RunGraphResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphResponse}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v1alpha_graph_pb.StructValue;
      reader.readMessage(value,v1alpha_graph_pb.StructValue.deserializeBinaryFromReader);
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    case 3:
      var value = new v1alpha_signature_pb.TypeErrors;
      reader.readMessage(value,v1alpha_signature_pb.TypeErrors.deserializeBinaryFromReader);
      msg.setTypeErrors(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.runtime.RunGraphResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.runtime.RunGraphResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      v1alpha_graph_pb.StructValue.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTypeErrors();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      v1alpha_signature_pb.TypeErrors.serializeBinaryToWriter
    );
  }
};


/**
 * optional tierkreis.v1alpha.graph.StructValue success = 1;
 * @return {?proto.tierkreis.v1alpha.graph.StructValue}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.getSuccess = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.StructValue} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.StructValue, 1));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.StructValue|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphResponse} returns this
*/
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.tierkreis.v1alpha.runtime.RunGraphResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphResponse} returns this
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.clearSuccess = function() {
  return this.setSuccess(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.hasSuccess = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string error = 2;
 * @return {string}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphResponse} returns this
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.setError = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.tierkreis.v1alpha.runtime.RunGraphResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphResponse} returns this
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.clearError = function() {
  return jspb.Message.setOneofField(this, 2, proto.tierkreis.v1alpha.runtime.RunGraphResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional tierkreis.v1alpha.signature.TypeErrors type_errors = 3;
 * @return {?proto.tierkreis.v1alpha.signature.TypeErrors}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.getTypeErrors = function() {
  return /** @type{?proto.tierkreis.v1alpha.signature.TypeErrors} */ (
    jspb.Message.getWrapperField(this, v1alpha_signature_pb.TypeErrors, 3));
};


/**
 * @param {?proto.tierkreis.v1alpha.signature.TypeErrors|undefined} value
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphResponse} returns this
*/
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.setTypeErrors = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.tierkreis.v1alpha.runtime.RunGraphResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.runtime.RunGraphResponse} returns this
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.clearTypeErrors = function() {
  return this.setTypeErrors(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.runtime.RunGraphResponse.prototype.hasTypeErrors = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.tierkreis.v1alpha.runtime);
