// source: v1alpha/worker.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var v1alpha_graph_pb = require('../v1alpha/graph_pb.js');
goog.object.extend(proto, v1alpha_graph_pb);
var v1alpha_runtime_pb = require('../v1alpha/runtime_pb.js');
goog.object.extend(proto, v1alpha_runtime_pb);
goog.exportSymbol('proto.tierkreis.v1alpha.worker.RunFunctionRequest', null, global);
goog.exportSymbol('proto.tierkreis.v1alpha.worker.RunFunctionResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.worker.RunFunctionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.worker.RunFunctionRequest.displayName = 'proto.tierkreis.v1alpha.worker.RunFunctionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tierkreis.v1alpha.worker.RunFunctionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tierkreis.v1alpha.worker.RunFunctionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tierkreis.v1alpha.worker.RunFunctionResponse.displayName = 'proto.tierkreis.v1alpha.worker.RunFunctionResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.worker.RunFunctionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.worker.RunFunctionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pb_function: (f = msg.getFunction()) && v1alpha_graph_pb.FunctionName.toObject(includeInstance, f),
    inputs: (f = msg.getInputs()) && v1alpha_graph_pb.StructValue.toObject(includeInstance, f),
    loc: (f = msg.getLoc()) && v1alpha_graph_pb.Location.toObject(includeInstance, f),
    callback: (f = msg.getCallback()) && v1alpha_runtime_pb.Callback.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionRequest}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.worker.RunFunctionRequest;
  return proto.tierkreis.v1alpha.worker.RunFunctionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.worker.RunFunctionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionRequest}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v1alpha_graph_pb.FunctionName;
      reader.readMessage(value,v1alpha_graph_pb.FunctionName.deserializeBinaryFromReader);
      msg.setFunction(value);
      break;
    case 2:
      var value = new v1alpha_graph_pb.StructValue;
      reader.readMessage(value,v1alpha_graph_pb.StructValue.deserializeBinaryFromReader);
      msg.setInputs(value);
      break;
    case 3:
      var value = new v1alpha_graph_pb.Location;
      reader.readMessage(value,v1alpha_graph_pb.Location.deserializeBinaryFromReader);
      msg.setLoc(value);
      break;
    case 4:
      var value = new v1alpha_runtime_pb.Callback;
      reader.readMessage(value,v1alpha_runtime_pb.Callback.deserializeBinaryFromReader);
      msg.setCallback(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.worker.RunFunctionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.worker.RunFunctionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFunction();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      v1alpha_graph_pb.FunctionName.serializeBinaryToWriter
    );
  }
  f = message.getInputs();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      v1alpha_graph_pb.StructValue.serializeBinaryToWriter
    );
  }
  f = message.getLoc();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      v1alpha_graph_pb.Location.serializeBinaryToWriter
    );
  }
  f = message.getCallback();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      v1alpha_runtime_pb.Callback.serializeBinaryToWriter
    );
  }
};


/**
 * optional tierkreis.v1alpha.graph.FunctionName function = 1;
 * @return {?proto.tierkreis.v1alpha.graph.FunctionName}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.getFunction = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.FunctionName} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.FunctionName, 1));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.FunctionName|undefined} value
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionRequest} returns this
*/
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.setFunction = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionRequest} returns this
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.clearFunction = function() {
  return this.setFunction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.hasFunction = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional tierkreis.v1alpha.graph.StructValue inputs = 2;
 * @return {?proto.tierkreis.v1alpha.graph.StructValue}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.getInputs = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.StructValue} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.StructValue, 2));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.StructValue|undefined} value
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionRequest} returns this
*/
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.setInputs = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionRequest} returns this
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.clearInputs = function() {
  return this.setInputs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.hasInputs = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional tierkreis.v1alpha.graph.Location loc = 3;
 * @return {?proto.tierkreis.v1alpha.graph.Location}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.getLoc = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.Location} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.Location, 3));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.Location|undefined} value
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionRequest} returns this
*/
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.setLoc = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionRequest} returns this
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.clearLoc = function() {
  return this.setLoc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.hasLoc = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional tierkreis.v1alpha.runtime.Callback callback = 4;
 * @return {?proto.tierkreis.v1alpha.runtime.Callback}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.getCallback = function() {
  return /** @type{?proto.tierkreis.v1alpha.runtime.Callback} */ (
    jspb.Message.getWrapperField(this, v1alpha_runtime_pb.Callback, 4));
};


/**
 * @param {?proto.tierkreis.v1alpha.runtime.Callback|undefined} value
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionRequest} returns this
*/
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.setCallback = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionRequest} returns this
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.clearCallback = function() {
  return this.setCallback(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.worker.RunFunctionRequest.prototype.hasCallback = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tierkreis.v1alpha.worker.RunFunctionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.tierkreis.v1alpha.worker.RunFunctionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tierkreis.v1alpha.worker.RunFunctionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.worker.RunFunctionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    outputs: (f = msg.getOutputs()) && v1alpha_graph_pb.StructValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionResponse}
 */
proto.tierkreis.v1alpha.worker.RunFunctionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tierkreis.v1alpha.worker.RunFunctionResponse;
  return proto.tierkreis.v1alpha.worker.RunFunctionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tierkreis.v1alpha.worker.RunFunctionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionResponse}
 */
proto.tierkreis.v1alpha.worker.RunFunctionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v1alpha_graph_pb.StructValue;
      reader.readMessage(value,v1alpha_graph_pb.StructValue.deserializeBinaryFromReader);
      msg.setOutputs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tierkreis.v1alpha.worker.RunFunctionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tierkreis.v1alpha.worker.RunFunctionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tierkreis.v1alpha.worker.RunFunctionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tierkreis.v1alpha.worker.RunFunctionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOutputs();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      v1alpha_graph_pb.StructValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional tierkreis.v1alpha.graph.StructValue outputs = 1;
 * @return {?proto.tierkreis.v1alpha.graph.StructValue}
 */
proto.tierkreis.v1alpha.worker.RunFunctionResponse.prototype.getOutputs = function() {
  return /** @type{?proto.tierkreis.v1alpha.graph.StructValue} */ (
    jspb.Message.getWrapperField(this, v1alpha_graph_pb.StructValue, 1));
};


/**
 * @param {?proto.tierkreis.v1alpha.graph.StructValue|undefined} value
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionResponse} returns this
*/
proto.tierkreis.v1alpha.worker.RunFunctionResponse.prototype.setOutputs = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tierkreis.v1alpha.worker.RunFunctionResponse} returns this
 */
proto.tierkreis.v1alpha.worker.RunFunctionResponse.prototype.clearOutputs = function() {
  return this.setOutputs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tierkreis.v1alpha.worker.RunFunctionResponse.prototype.hasOutputs = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.tierkreis.v1alpha.worker);
